name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      # setup-swift doesn't support Swift 6 so use the Swift included in macos-latest.
      # - name: Set up Swift
      #   uses: swift-actions/setup-swift@v2
      #   with:
      #     swift-version: "6.0.0"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Formatting
        run: swift format lint --strict --recursive Sources Tests Package.swift

      - name: Build
        run: swift build

      - name: Run tests
        run: swift test
